name: 'Voxelite plugin.json validator'
description: 'Validate your plugin.json file'
inputs:
  file:
    description: 'File to check'
    required: true
    default: 'plugin.json'
  official:
    description: 'Set to `true` for official plugins, otherwise shows some warning when the plugin looks too official'
    default: 'false'
outputs:
  codename:
    description: 'Plugin codename'
  version:
    description: 'Plugin version'
  alias:
    description: 'Alternative plugin codenames separated by a comma'
  depends:
    description: 'Comma-separated plugins this one directly depends on'
  other_plugins:
    description: 'Comma-separated plugins mentioned in plugin relation fields'
runs:
  using: 'node20'
  main: 'index.js'
