on: [push]

jobs:
  plugin_json:
    runs-on: ubuntu-latest
    name: Test some plugin.json files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM packages
        run: |
          npm install @actions/core
          npm install @actions/github

      - name: Test minimal.json
        uses: ./
        with:
          file: test/minimal.json

      - name: Test full.json
        uses: ./
        with:
          file: test/full.json
