on: [push]

jobs:
  minimal:
    runs-on: ubuntu-latest
    name: Minimal plugin.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test minimal.json
        id: plugin
        uses: ./
        with:
          file: test/minimal.json

      - name: Plugin info
        shell: bash
        run: |
          echo "Codename: ${{steps.plugin.outputs.codename}}"
          echo "Version: ${{steps.plugin.outputs.version}}"

  full:
    runs-on: ubuntu-latest
    name: Full plugin.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: plugin.json
        id: plugin
        uses: ./
        with:
          file: test/full.json

      - name: Plugin info
        shell: bash
        run: |
          echo "Codename: ${{steps.plugin.outputs.codename}}"
          echo "Version: ${{steps.plugin.outputs.version}}"
