name: Test behaviour

on: [push]

jobs:
  full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin_file: [ 'minimal.json', 'full.json' ]
    name: ${{ matrix.plugin_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: plugin.json
        id: plugin
        uses: ./
        with:
          file: 'test/${{ matrix.plugin_file }}'

      - name: Plugin info
        shell: bash
        run: |
          echo "Codename: ${{steps.plugin.outputs.codename}}"
          echo "Version: ${{steps.plugin.outputs.version}}"
          echo "Alias: ${{steps.plugin.outputs.alias}}"
          echo "Other Plugins: ${{steps.plugin.outputs.other_plugins}}"
